export const EffectData = {
  explosion: {
    name: "explode",
    src: "/assets/boomEffect.png",
    frameWidth: 69,
    frameHeight: 60,
    animation: {
      key: "explode",
      start: 0,
      end: 24,
      frameRate: 20,
      repeat: 0,
    },
  },
  newExplosion: {
    name: "newExplode",
    src: "/assets/destroy.png",
    frameWidth: 517,
    frameHeight: 517,
    animation: {
      key: "newExplode",
      start: 0,
      end: 29,
      frameRate: 15,
      repeat: 0,
    },
  },
  bigHit: {
    name: "bigHitExplode",
    src: "/assets/bigHit.png",
    frameWidth: 120,
    frameHeight: 109,
    animation: {
      key: "bigHitExplode",
      start: 0,
      end: 34,
      frameRate: 60,
      repeat: 0,
    },
  },
  spaceShip: {
    name: "spaceShip",
    src: "/assets/spaceShip.png",
    frameWidth: 32,
    frameHeight: 32,
    animation: {
      key: "spaceShip",
      start: 0,
      end: 2,
      frameRate: 3,
      repeat: 0,
    },
  },
  spaceShip_straight: {
    name: "spaceShip_straight",
    src: "/assets/spaceShip_straight.png",
    frameWidth: 32,
    frameHeight: 44,
    animation: {
      key: "spaceShip_straight",
      start: 0,
      end: 3,
      frameRate: 16,
      repeat: 0,
    },
  },
  spaceShip_left: {
    name: "spaceShip_left",
    src: "/assets/spaceShip_left.png",
    frameWidth: 32,
    frameHeight: 44,
    animation: {
      key: "spaceShip_left",
      start: 0,
      end: 3,
      frameRate: 16,
      repeat: 0,
    },
  },
  spaceShip_right: {
    name: "spaceShip_right",
    src: "/assets/spaceShip_right.png",
    frameWidth: 32,
    frameHeight: 44,
    animation: {
      key: "spaceShip_right",
      start: 0,
      end: 3,
      frameRate: 16,
      repeat: 0,
    },
  },
  announcer: {
    name: "announcer",
    src: "/assets/announcer.png",
    frameWidth: 32,
    frameHeight: 32,
    animation: {
      key: "announcer",
      start: 0,
      end: 4,
      frameRate: 10,
      repeat: -1,
    },
  },
  enemyDestory: {
    name: "enemyDestory",
    src: "/assets/enemyDestory.png",
    frameWidth: 40,
    frameHeight: 40,
    animation: {
      key: "enemyDestory",
      start: 0,
      end: 3,
      frameRate: 8,
      repeat: 0,
    },
  },
};
